travis:
  secure:
    BINSTAR_TOKEN: h0uxoxcH+YZV0277+7gUKm3gahV4K6AhvjEUG170pJZqlyYFQhVPhVFo94higjQRDK1qoKMRTFXCzWBAtk8syVq8baViN+mNwQNpYifIsPaVuKfBae7RNHCaJLL9zQeSqh9JzF4x+9evQ3X19G0O297OzFqVG25LsTJczqKfrPUfRzhMZ6nuYbP37eEBbkKdeSykQnH69JZj0fvxwsxxVn0itnqyzik9PEIz7R83ykEOXUyXTqcpqp5X/8ClsTd4jYd9rDGJrRXYnpJPPsCB8eq5EEcgC6aPyTP9lQFKsQks51ViNfYTbK9wHHhU86J1Ii1SYWC0+l0NfW/X08B0vkN9QqTHutaEMaSy05Pz2KWdeitmcfU5VgHZzu8ra4LO5GdQ469UUZ/o3xa6conk9+YTBWrefQmQGDW9hio63jYw11tlUge/HCkF8aiUcHWlPvw3XV+QKHMZ5YLIWHkM9X9zKlJYTfAnMi2KOM7zuNmPXCSk69py/PpHRxLxC+tLA82p2TTdlo/H3vbmBWk5XaHqIf2990U2RjNcOS0WBoNumgt9oP1uLBhENM7aHPB7joXUUCqp0xXIVCB8YLo3G2kj8FT3hjr1+xdpfItATQ93ZBlrcF4p0KCggGZs0qaXi1Zv/uaxG9m4iqBW254LVkOQQlrF7UXhH9lQs05pw7w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
